FROM fdev321123/runner-devcontainer:latest

# Following the pattern of Dockerfile and base.Dockerfile established here https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux/.devcontainer
